Description: |
  Uploads a computer configuration to the Jamf Pro Server and creates a Self Service Policy and Smart Group.

  This profile is for the production version of Carbon Copy Cloner. At certain times, the license key changes, so we need a separate profile for untested and tested versions.

  Required override keys:
  - REGISTRATION_CODE
  - REGISTRATION_EMAIL
  - REGISTRATION_NAME
  - REGISTRATION_PRODUCT_NAME
Identifier: com.github.eth-its-recipes.jamf.CarbonCopyCloner-settings-prod-profile
MinimumVersion: "2.3"

Input:
  NAME: Carbon Copy Cloner
  LANGUAGE: EN
  JSS_INVENTORY_NAME: "%NAME%.app"
  IDENTIFIER: com.bombich.ccc
  INSTALLED_GROUP_NAME: "%NAME% %LANGUAGE% installed"
  TESTING_GROUP_NAME: Testing
  TESTING_GROUP_TEMPLATE: StaticGroup-testing.xml
  EXCLUSION_GROUP_NAME: "%TESTING_GROUP_NAME%"
  PROFILE_CATEGORY: Application Settings
  PROFILE_NAME: Carbon Copy Cloner
  PROFILE_DESCRIPTION: License and settings for Carbon Copy Cloner (v6)
  ORGANIZATION: "%NAME%"
  PROFILE_TEMPLATE: Profile-1-group-1-exclusion.xml
  PROFILE_PAYLOAD: "%IDENTIFIER%.plist"
  REPLACE_PROFILE: "True"

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%PROFILE_CATEGORY%"
      replace_category: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%TESTING_GROUP_TEMPLATE%"
      computergroup_name: "%TESTING_GROUP_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerProfileUploader
    Arguments:
      profile_name: "%PROFILE_NAME%"
      profile_category: "%PROFILE_CATEGORY%"
      profile_template: "%PROFILE_TEMPLATE%"
      payload: "%PROFILE_PAYLOAD%"
      identifier: "%IDENTIFIER%"
      organization: "%ORGANIZATION%"
      profile_description: "%PROFILE_DESCRIPTION%"
      profile_computergroup: "%INSTALLED_GROUP_NAME%"
      replace_profile: "%REPLACE_PROFILE%"
