Description: |
  Uploads a computer configuration to the Jamf Pro Server and creates a Self Service Policy and Smart Group.
Identifier: com.github.eth-its-recipes.jamf.Nudge-settings-profile
MinimumVersion: "2.3"

Input:
  NAME: Nudge
  IDENTIFIER: com.github.macadmins.nudge
  PROFILE_CATEGORY: Administration
  ORGANIZATION: ETH Zuerich
  PROFILE_TEMPLATE: Profile-all-computers.xml
  PROFILE_DESCRIPTION: ETH Nudge Settings
  PROFILE_NAME: "%NAME% Settings"
  PROFILE_PAYLOAD: "%IDENTIFIER%.plist"
  REPLACE_PROFILE: "True"

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%PROFILE_CATEGORY%"
      replace_category: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerProfileUploader
    Arguments:
      profile_name: "%PROFILE_NAME%"
      profile_category: "%PROFILE_CATEGORY%"
      profile_template: "%PROFILE_TEMPLATE%"
      payload: "%PROFILE_PAYLOAD%"
      identifier: "%IDENTIFIER%"
      organization: "%ORGANIZATION%"
      profile_description: "%PROFILE_DESCRIPTION%"
      replace_profile: "%REPLACE_PROFILE%"