Comments: Apple Configurator 2 must be installed on the AutoPkg host via VPP managed app distribution or similar process.
Description: Uploads the pkg to the JSS, and creates a Self-Service Policy available to members of a Testing group.
Identifier: com.github.eth-its-recipes.jamf.AppleConfigurator2
MinimumVersion: "2.3"
ParentRecipe: com.github.nmcspadden.pkg.appstore

Input:
  NAME: Apple Configurator 2
  PATH: "/Applications/%NAME%.app"
  POLICY_NAME: "%NAME% (Testing)"
  SELFSERVICE_DISPLAY_NAME: "%NAME% (Testing)"
  PKG_CATEGORY: Tools & Accessories
  SELFSERVICE_DESCRIPTION: |
    Apple Configurator 2 can be used to restore iPhone, iPad, iPod Touch, Apple TV and Apple Silicon Mac to factory settings.

    Version: %version%
    Category: %PKG_CATEGORY%
  OS_EXCLUDE_MAX: 10.14.5
  OS_EXCLUDE_MAX_GROUP_NAME: "macOS %OS_EXCLUDE_MAX% or less"
  OS_EXCLUDE_MAX_GROUP_TEMPLATE: SmartGroup-OS-exclude-max.xml
  TEST_VERSION_INSTALLED_GROUP_NAME: "%NAME% test version installed"
  TEST_VERSION_INSTALLED_GROUP_TEMPLATE: SmartGroup-test-version-installed.xml
  TESTING_GROUP_NAME: Testing
  TESTING_GROUP_TEMPLATE: StaticGroup-testing.xml
  TEST_USERS_GROUP_NAME: "%NAME% test users"
  TEST_USERS_GROUP_TEMPLATE: SmartGroup-test-users.xml
  POLICY_CATEGORY: Untested
  INSTALL_BUTTON_TEXT: "Install %version%"
  REINSTALL_BUTTON_TEXT: "Install %version%"
  POLICY_TEMPLATE: Policy-untested-selfservice-OS-exclude-max.xml
  SELFSERVICE_ICON: "%NAME% 2.15.png"
  POLICY_RUN_COMMAND: "echo 'Installation of %NAME% complete'"
  UPDATE_PREDICATE: "pkg_uploaded != True"

Process:
  - Processor: com.github.grahampugh.recipes.commonprocessors/VersionRegexGenerator

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%PKG_CATEGORY%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
    Arguments:
      pkg_category: "%PKG_CATEGORY%"

  - Processor: com.github.grahampugh.recipes.commonprocessors/WritePkgResultToJson

  - Processor: StopProcessingIf
    Arguments:
      predicate: "%UPDATE_PREDICATE%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%POLICY_CATEGORY%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%TESTING_GROUP_TEMPLATE%"
      computergroup_name: "%TESTING_GROUP_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_name: "%TEST_USERS_GROUP_NAME%"
      computergroup_template: "%TEST_USERS_GROUP_TEMPLATE%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_name: "%OS_EXCLUDE_MAX_GROUP_NAME%"
      computergroup_template: "%OS_EXCLUDE_MAX_GROUP_TEMPLATE%"
      replace_group: "True"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_name: "%TEST_VERSION_INSTALLED_GROUP_NAME%"
      computergroup_template: "%TEST_VERSION_INSTALLED_GROUP_TEMPLATE%"
      replace_group: "True"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments:
      policy_template: "%POLICY_TEMPLATE%"
      policy_name: "%POLICY_NAME%"
      icon: "%SELFSERVICE_ICON%"
      replace_policy: "True"

  - Processor: com.github.grahampugh.recipes.postprocessors/LastRecipeRunResult
